export const TIME_RANGES: Record<number, string> = {
  0: "1h",
  1: "6h",
  2: "1d",
  3: "1w",
  4: "2w",
  5: "3w",
  6: "1m",
  7: "2m",
  8: "3m",
  9: "6m",
  10: "1y",
  11: "2y",
  12: "∞",
};

export const FUND_UI_MAX = 10_000_000;

export const NETWORK_DISPLAY_NAMES: Record<string, string> = {
  ethereum: "Ethereum",
  binance: "Binance",
  optimism: "Optimism",
  base: "Base",
  arbitrum: "Arbitrum",
  polygon: "Polygon",
  avalanche: "Avalanche",
  gnosis: "Gnosis",
  linea: "Linea",
  scroll: "Scroll",
  mantle: "Mantle",
  megaeth: "MegaETH",
  "polygon-zkevm": "Polygon zkEVM",
  "arbitrum-nova": "Arbitrum Nova",
  celo: "Celo",
  cronos: "Cronos",
  moonbeam: "Moonbeam",
  moonriver: "Moonriver",
  opbnb: "opBNB",
};

export const NETWORK_KEYS = Object.keys(NETWORK_DISPLAY_NAMES);

export const EXPLORER_MAP: Record<string, string> = {
  ethereum: "https://etherscan.io/address/",
  binance: "https://bscscan.com/address/",
  optimism: "https://optimistic.etherscan.io/address/",
  arbitrum: "https://arbiscan.io/address/",
  polygon: "https://polygonscan.com/address/",
  base: "https://basescan.org/address/",
  avalanche: "https://snowtrace.io/address/",
  fantom: "https://ftmscan.com/address/",
  gnosis: "https://gnosisscan.io/address/",
  linea: "https://lineascan.build/address/",
  scroll: "https://scrollscan.com/address/",
  mantle: "https://mantlescan.xyz/address/",
  megaeth: "https://mega.etherscan.io/address/",
  "polygon-zkevm": "https://zkevm.polygonscan.com/address/",
  "arbitrum-nova": "https://nova.arbiscan.io/address/",
  celo: "https://celoscan.io/address/",
  cronos: "https://cronoscan.com/address/",
  moonbeam: "https://moonscan.io/address/",
  moonriver: "https://moonriver.moonscan.io/address/",
  opbnb: "https://opbnb.bscscan.com/address/",
};

export const TX_EXPLORER_MAP: Record<string, string> = {
  ethereum: "https://etherscan.io/tx/",
  binance: "https://bscscan.com/tx/",
  optimism: "https://optimistic.etherscan.io/tx/",
  arbitrum: "https://arbiscan.io/tx/",
  polygon: "https://polygonscan.com/tx/",
  base: "https://basescan.org/tx/",
  avalanche: "https://snowtrace.io/tx/",
  fantom: "https://ftmscan.com/tx/",
  gnosis: "https://gnosisscan.io/tx/",
  linea: "https://lineascan.build/tx/",
  scroll: "https://scrollscan.com/tx/",
  mantle: "https://mantlescan.xyz/tx/",
  megaeth: "https://mega.etherscan.io/tx/",
  "polygon-zkevm": "https://zkevm.polygonscan.com/tx/",
  "arbitrum-nova": "https://nova.arbiscan.io/tx/",
  celo: "https://celoscan.io/tx/",
  cronos: "https://cronoscan.com/tx/",
  moonbeam: "https://moonscan.io/tx/",
  moonriver: "https://moonriver.moonscan.io/tx/",
  opbnb: "https://opbnb.bscscan.com/tx/",
};

export const NETWORK_COLORS: Record<string, string> = {
  ethereum: "bg-blue-500",
  binance: "bg-yellow-500",
  optimism: "bg-red-500",
  base: "bg-sky-500",
  arbitrum: "bg-blue-600",
  polygon: "bg-purple-500",
  avalanche: "bg-rose-600",
  fantom: "bg-indigo-600",
  gnosis: "bg-emerald-600",
  linea: "bg-teal-600",
  scroll: "bg-lime-600",
  mantle: "bg-amber-600",
  megaeth: "bg-violet-600",
  "polygon-zkevm": "bg-fuchsia-600",
  "arbitrum-nova": "bg-cyan-500",
  celo: "bg-emerald-500",
  cronos: "bg-orange-500",
  moonbeam: "bg-pink-600",
  moonriver: "bg-rose-500",
  opbnb: "bg-yellow-600",
};

export const NETWORK_NATIVE_CONFIG: Record<
  string,
  { symbol: string; decimals: number }
> = {
  ethereum: { symbol: "ETH", decimals: 18 },
  base: { symbol: "ETH", decimals: 18 },
  optimism: { symbol: "ETH", decimals: 18 },
  arbitrum: { symbol: "ETH", decimals: 18 },
  linea: { symbol: "ETH", decimals: 18 },
  scroll: { symbol: "ETH", decimals: 18 },
  megaeth: { symbol: "ETH", decimals: 18 },
  binance: { symbol: "BNB", decimals: 18 },
  opbnb: { symbol: "BNB", decimals: 18 },
  avalanche: { symbol: "AVAX", decimals: 18 },
  polygon: { symbol: "POL", decimals: 18 },
  mantle: { symbol: "MNT", decimals: 18 },
  gnosis: { symbol: "xDAI", decimals: 18 },
  celo: { symbol: "CELO", decimals: 18 },
  cronos: { symbol: "CRO", decimals: 18 },
  moonbeam: { symbol: "GLMR", decimals: 18 },
  moonriver: { symbol: "MOVR", decimals: 18 },
};
